"""create_table_user

Revision ID: e90aaa350505
Revises: 
Create Date: 2024-06-10 11:30:56.649588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e90aaa350505'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=65), nullable=False),
                    sa.Column('email', sa.String(length=150), nullable=False),
                    sa.Column('password', sa.String(length=65), nullable=False),
                    sa.Column('full_name', sa.String(length=100), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('verify_code', sa.String(length=6), nullable=True),
                    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'FRESHER', 'MEMBER', name='userrole'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
